easy_admin:
  site_name: 'Intranet ADMIN'
  design:
    menu:
      - label: 'Users'
        icon: 'users'
        children:
          - { label: 'Users', entity: 'All'}
          - 'Students'
          - 'Teachers'
      - 'Disciplines'
      - 'Notes'
  entities:
    All:
      disabled_actions: ['new','show']
      class: App\Entity\User
      list:
        fields:
          - email
          - firstname
          - lastname
          - roles
      form:
        fields:
          - email
          - firstname
          - lastname
          - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN','ROLE_TEACHER':'ROLE_TEACHER' } } }
    Students:
      disabled_actions: ['new','show']
      class: App\Entity\User
      list:
        dql_filter: "entity.roles LIKE '%%[]%%'"
        fields:
          - email
          - firstname
          - lastname
          - { property: 'disciplines', type: 'json_array'}
      form:
        fields:
          - email
          - firstname
          - lastname
    Teachers:
      disabled_actions: ['new','show']
      class: App\Entity\User
      list:
        dql_filter: "entity.roles LIKE '%%ROLE_TEACHER%%'"
        fields:
          - email
          - firstname
          - lastname
          - { property: 'disciplines', type: 'json_array'}
      form:
        fields:
          - email
          - firstname
          - lastname
          - { property: 'disciplines', type_options: { 'by_reference': false } }
    Disciplines:
      disabled_actions: ['show']
      class: App\Entity\Discipline
      list:
        fields:
          - discipline
      form:
        fields:
          - discipline
    Notes:
      disabled_actions: ['show']
      class: App\Entity\Note
      list:
        fields:
          - note
          - comment
          - user
          - discipline
