easy_admin:
  site_name: 'Intranet ADMIN'
  design:
    menu:
      - label: 'Users'
        icon: 'users'
        children: ['All','Students', 'Teachers']
      - 'Discipline'
      - 'Note'
  entities:
    All:
      disabled_actions: ['new']
      class: App\Entity\User
      list:
        fields:
          - email
          - firstname
          - lastname
          - roles
          - { property: 'disciplines', type: 'json_array' }
      form:
        fields:
          - email
          - firstname
          - lastname
          - { property: 'disciplines', type_options: { 'by_reference': false } }

          # if administrators are allowed to edit users' passwords and roles, add this:
          - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN','ROLE_TEACHER':'ROLE_TEACHER' } } }

    Students:
      disabled_actions: ['new']
      class: App\Entity\User
      list:
        dql_filter: "entity.roles LIKE '%%[]%%'"
        fields:
          - email
          - firstname
          - lastname
          - { property: 'disciplines', type: 'json_array'}
      form:
        fields:
          - email
          - firstname
          - lastname
          - { property: 'disciplines', type_options: { 'by_reference': false } }
          # - { property: 'disciplines', type: 'json_array'}
          # - { property: 'grades', type: 'json_array'}
    Teachers:
      disabled_actions: ['new']
      class: App\Entity\User
      list:
        dql_filter: "entity.roles LIKE '%%[]%%'"
        fields:
          - email
          - firstname
          - lastname
          - { property: 'disciplines', type: 'json_array'}
      form:
        fields:
          - email
          - firstname
          - lastname
          - { property: 'disciplines', type_options: { 'by_reference': false } }
          # - { property: 'disciplines', type: 'json_array'}
          # - { property: 'grades', type: 'json_array'}
    Discipline:
      #disabled_actions: ['show',  'search']
      class: App\Entity\Discipline
      list:
        fields:
          - discipline
         # - { property: 'user', type: 'json_array'}
      form:
               #dql_filter: "entity.roles NOT LIKE '%%env(ROLE_ADMIN)%%'"
        #dql_filter: "entity.roles LIKE '%%['ROLE_ADMIN']%%'"
        #dql_filter: "entity.roles LIKE '%%env(ROLE_ADMIN)%%'"
        fields:
         # - user
          - discipline
         # - grade
    Note:
      class: App\Entity\Note
      list:
        fields:
          - note
          - { property: 'discipline', type: 'json_array'}
          - { property: 'user', type: 'json_array'}
